check for right versions of bash, getop, make syntax corrections

diff --git a/dtxgen b/dtxgen
--- a/dtxgen
+++ b/dtxgen
@@ -9,13 +9,13 @@ Myname="${0##*/}"
 = Synopsis
 dtxgen [options] basename.[sty,cls]	
 
-= Options
+== Options
 -h,--help	print short help and exit
 -H,--Help	print full documentation via less and exit
 -V,--version	print version and exit
 -s,--short	short, one-liner, package description
 -d,--date	initial version's date. Default: current date 
--m,--mail	your email address. Default: |$MAIL|
+-m,--mail	your email address. Default: |$EMAIL|
 -n,--name	your name. Default: |$NAME|
 -c,--class	(class packs only) class to be preloaded. Default: article
 -q,--quiet	run quietly
@@ -101,6 +101,14 @@ zip		produce a zip file ready for upload to CTAN
 Released under the [GNU General Public License](www.gnu.org/copyleft/gpl.html)
 DOC
 
+# check executables and versions of bash and getopt
+((BASH_VERSINFO>=4)) || die "Need bash version >= 4"
+for i in getopt make; do
+   command -v "$i" &> /dev/null || die "$i: command not found"
+done
+i=$(getopt -T)
+{ (($?==4)) && [[ -z $i ]]; } || die "Your getopt is not GNU"
+
 # using the label in arg 2, read template from my self, filter it
 # through the script in arg 1, and write the output to the file in arg 3.
 # The default for arg 3 is arg 2
@@ -148,7 +156,7 @@ while [ $# -gt 0 ]; do
                   date=$2
                   shift 2
                   ;;
-   (-m|--mail)    # your email address. Default: $MAIL
+   (-m|--mail)    # your email address. Default: $EMAIL
                   mail=$2
                   shift 2
                   ;;
@@ -209,7 +217,7 @@ esac
 shrt=$(sed 's/\\[[:alpha:]]\\+{\\([^}]*\\)}/\\1/g;s/\\//g' <<<"$short")
 
 # Any \'s in the short description need to be duplicated for the script:
-short=$(sed 's/\\/\\\\/g' <<<"$short")
+short="${short//\\/\\\\}"
 
 test -z "$mail" && die "author's email not set - use option or environment variable EMAIL"
 test -z "$name" && die "author's name not set - use option or environment variable NAME"
@@ -227,20 +235,16 @@ declare -A rm=(
       [See]='http://www.latex-project.org/lppl.txt'
 )
 
-readme=()
-
 for i in $kopl $base Author E-mail License See; do
-   readme+="$(printf "%*s:| %s°"  $colw "$i" "${rm[$i]}")"
+  readme+="$(printf "%*s:| %s\\\\n"  $colw "$i" "${rm[$i]}")"
 done
 
 # make sed script replacing the variables in the templates:
 sedscript=''
-for i in readme base year ext mail use typ Typ name date short shrt lcl; do
-  eval v="\$$i"
-  test $quiet || echo "$i	$v"|sed 's/\\\\/\\/g;s=°=\n=g'
-  sedscript="${sedscript}s=%$i%=$v=g;"
+for i in base year ext mail use typ Typ name date short shrt lcl readme; do
+  test $quiet || eval "echo -e \"$i	\$$i\""|sed 's/\\\\/\\/g'
+  eval "sedscript+=\"s=%$i%=\$$i=g;\""
 done
-sedscript+='s=°=\n=g'
 
 createfile "$sedscript" Makefile
 createfile "$sedscript" DTX "$base.dtx"
