added --body option; removed create_file(), using envsubst from gettext-base

diff --git a/dtxgen b/dtxgen
--- a/dtxgen
+++ b/dtxgen
@@ -22,9 +22,10 @@ dtxgen [options] basename.[sty,cls]
 -q,--quiet	run quietly
 
 = Description
-dtxgen creates a template for a self-extracting .dtx file, based on the model described by
-[Joseph Wright](www.texdev.net/2009/10/06/a-model-dtx-file/). It is useful for
-those who plan to create a new Documented LaTeX Source (.dtx) file.
+dtxgen creates a template for a self-extracting .dtx file, based on the
+model described by [Joseph Wright](www.texdev.net/2009/10/06/a-model-dtx-file/).
+It is useful for those who plan to create a new Documented LaTeX Source
+(.dtx) file.
 
 Usage example:
 
@@ -48,7 +49,7 @@ NAME and EMAIL, you could simply type:
   dtxgen myclass.cls
 
 and you would end up with five files: |myclass.dtx|, |myclass.cls|,
-|myclass.pdf|, |README|, and |Makefile|.
+|myclass.pdf|, |README.md|, and |Makefile|.
 
 = Options
 dtxgen recognizes the following options:
@@ -87,13 +88,14 @@ dtxgen recognizes the following options:
 	print full documentation via less and exit
 
 = Makefile
-The |Makefile| can be used to compile new versions of your work; it contains the following targets:
+The |Makefile| can be used to compile new versions of your work; it
+contains the following targets:
 
 all		(the default) generate the style or class file, the pdf-documentation,
-		and a README file.
+		and a README.md file.
 distclean	remove all files that can be regenerated,
 clean		same, except the style or class file, the pdf-documentation,
-		and a README file.
+		and a README.md file.
 inst		install in the user's TeX tree,
 install		install in the local TeX tree (uses sudo)
 zip		produce a zip file ready for upload to CTAN
@@ -130,21 +132,12 @@ excheck() {
    (( $? == 4 )) || die "Your getopt is not GNU"
 }
 
-# using the label in arg 2, read template from my self, filter it
-# through the script in arg 1, and write the output to the file in arg 3.
-# The default for arg 3 is arg 2
-function createfile {
-   file=$3
-   test "$file" = "" && file=$2
-   sed -n "/^:<<'$2'/,/^$2/p" "$0" |tail -n +2 |head -n -1 |sed "$1" >"$file"
-}
-
 :<<'DOC' #----------------------------------------------------------------------
 = handle_options
 synopsis:	 handle_options "$@"
 description:	handle the options.
 globals used:	 Myname Version
-globals  set:	 args
+globals  set:	 args short date mail name loadclass format quiet redir
 returnsL	the number of remaining arguments
 DOC
 #-------------------------------------------------------------------------------
@@ -152,8 +145,8 @@ handle_options() {
    local options
    if ! options=$(getopt \
       -n "$Myname" \
-      -o s:n:m:c:d:hHVf:qI \
-      -l short:,name:,mail:,class:,date:,help,Help,version,quiet,format: -- "$@"
+      -o s:n:m:b:c:d:hHVf:qI \
+      -l short:,name:,mail:,body:,class:,date:,help,Help,version,quiet,format: -- "$@"
    ); then exit 1; fi
    eval set -- "$options"
    
@@ -177,11 +170,11 @@ handle_options() {
                      date=$2
                      shift 2
                      ;;
-      (-m|--mail)    # your email address. Default: $EMAIL
+      (-m|--mail)    # your email address. Default: |$EMAIL|
                      mail=$2
                      shift 2
                      ;;
-      (-n|--name)    # your name. Default: $NAME
+      (-n|--name)    # your name. Default: |$NAME|
                      name=$2
                      shift 2
                      ;;
@@ -193,8 +186,14 @@ handle_options() {
 		     format=$2
 		     shift 2
 		     ;;
+      (-b|--body  )  # existing style or class to be used instead of demo
+		     body="$2"
+		     [[ -z $body ]] && die "kpsewhich could not find $body"
+		     shift 2
+		     ;;
       (-q|--quiet)   # run quietly
                      quiet=--quiet
+		     redir='>/dev/null'
                      shift
                      ;;
       (-I)	     instscript "$Myname" ||
@@ -211,25 +210,12 @@ handle_options() {
    args=( "$@" )
 }
 
-excheck make getopt pdflatex makeindex zip ltxfileinfo kpsewhich
+excheck make getopt envsubst pdflatex makeindex zip ltxfileinfo kpsewhich
 
 handle_options "$@"
 set -- "${args[@]}"
 
 test $# == 1 || die "I need 1 argument"
-
-export year typ Typ lcl use # used in templates - shellcheck sees them as unused
-
-name=${name:-${NAME:-(not set)}}
-mail=${mail:-${EMAIL:-(not set)}}
-date=${date:-$(date +%Y%m%d)}
-year=${date:0:4}
-loadclass=${loadclass:-article}
-format=${format:-pdflatex}
-
-# date must be 8 digits; insert the two /'s:
-if [[ ! $date =~ ^[[:digit:]]{8}$ ]]; then die "illegal date"; fi
-date=$(sed 's/\(....\)\(..\)\(..\)/\1\\\/\2\\\/\3/' <<<"$date")
 
 # argument must have .cls or .sty extension:
 base=${1%.*}
@@ -237,16 +223,27 @@ ext=${1#*.}
 
 case "$ext" in
 (cls) typ=class; Typ=Class;
-      short=${short:-A new LaTeX class}
+      : "${short:=A new LaTeX class}"
       lcl='\\LoadClass[a4paper,fleqn]{'"$loadclass}"
-     ;;
+      ;;
 (sty) typ=package; Typ=Package;
-      short=${short:-A new LaTeX package}
-      use='\\usepackage{\\jobname}'
-     ;;
+      : "${short:=A new LaTeX package}"
+      use='\usepackage{\jobname}'
+      ;;
 (*)   die "The argument must have .cls or .sty extension
          (try the --help option)"
 esac
+
+
+: "${name:=${NAME:-(not set)}}"		# default name is envvar NAME
+: "${mail:=${EMAIL:-(not set)}}"	# default email is envvar MAIL
+: "${date:=$(date +%Y%m%d)}"		# default date is now
+: "${loadclass:=article}"		# default class to load is article
+: "${format:=pdflatex}"			# default formatter is pdflatex
+
+# date must be 8 digits; insert the two /'s:
+if [[ ! $date =~ ^[[:digit:]]{8}$ ]]; then die "illegal date: $date"; fi
+date=$(sed 's/\(....\)\(..\)\(..\)/\1\/\2\/\3/' <<<"$date")
 
 # The short description may contain TeX commands, but then we need
 # a version without them at some places; note that this removes only
@@ -259,188 +256,48 @@ short="${short//\\/\\\\}"
 test -z "$mail" && die "author's email not set - use option or environment variable EMAIL"
 test -z "$name" && die "author's name not set - use option or environment variable NAME"
 
-colw=${#base}
-(( colw = colw < 7 ? 7 : colw ))
-kopl="$(eval "printf '%.0s-' {1..$colw}")"
-kopr="$(eval "printf '%.0s-' {1..$((72-colw))}")"
-declare -A rm=(
-    [$kopl]=$kopr
-    [$base]=$shrt
-   [Author]=$name
-   [E-mail]=$mail
-  [License]='Released under the LaTeX Project Public License v1.3c or later'
-      [See]='http://www.latex-project.org/lppl.txt'
-)
+export abst body desc base format ext year mail use typ Typ name date
+export short shrt lcl makefile readme
 
-for i in $kopl $base Author E-mail License See; do
-  readme+="$(printf "%*s:| %s\\\\n" "$colw" "$i" "${rm[$i]}")"
-done
+if [[ -z $body ]]; then
+   # if no existing style/class file was given, use the demo one:
+   body="$(sed -n "/^:<<'BODY'/,/^BODY/{/BODY/!p}" "$0" |envsubst)"
+   desc="$(sed -n "/^:<<'DESC'/,/^DESC/{/DESC/!p}" "$0")"
+   abst="% This is a demo $Typ file"
+else
+   body=${body%.$ext}.$ext
+   body="$(kpsewhich "$body")"
+   [[ -z $body ]] && die "kpsewhich could not find $body"
+   # remove any \Provides..., \NeedsTeXFormat, \endinput and %%-comments
+   body="$(sed '
+	/^\\Provides/{N;N;s/\\Provides.*{.*}%*\s\+\[.*\]//;}
+	/^%%/d
+	/^\\NeedsTeXFormat/d
+	/^\\endinput
+   ' "$body")"
+   abst="% Put your abstract here"
+   desc="% Put your descriptive text here"
+fi
+makefile="$(sed -n "/^:<<'MAKE'/,/^MAKE/{/MAKE/!p}" "$0" |envsubst)"
+readme="$(sed -n "/^:<<'README'/,/^README/{/README/!p}" "$0" |envsubst)"
 
-# make sed script replacing the variables in the templates:
-sedscript=''
-for i in base format year ext mail use typ Typ name date short shrt lcl readme; do
-  test $quiet || eval "echo -e \"$i	\$$i\""|sed 's/\\\\/\\/g'
-  eval "sedscript+=\"s=%$i%=\$$i=g;\""
-done
+sed -n "/^:<<'DTX'/,/^DTX/{/DTX/!p}" "$0" |envsubst >"$base".dtx
 
-createfile "$sedscript" Makefile
-createfile "$sedscript" DTX "$base.dtx"
-make $quiet
+eval "luatex '$base.dtx' $redir" ||
+   die "Error running 'luatex $base.dtx'" 'see log(s)'
+
+make -f Makefile. $quiet || die 'Error running make'
+make $quiet clean
+cat <<-EOD
+	You have 5 new files now:
+	1. $base.dtx: this is the only file you need to keep and edit.
+	   The other files can be generated from it with:
+	   luatex $base.dtx; make -f Makefile.; make clean
+	2. Makefile: 
+EOD
 exit 0
-
 # ---- TEMPLATES: ----
-:<<'Makefile'
-NAME  = %base%
-SHELL = bash
-PWD   = $(shell pwd)
-FORMAT= %format%
-VERS  = $(shell ltxfileinfo -v $(NAME).dtx|sed -e 's/^v//')
-LOCAL = $(shell kpsewhich --var-value TEXMFLOCAL)
-UTREE = $(shell kpsewhich --var-value TEXMFHOME)
-all:	$(NAME).pdf
-	test -e README.txt && mv README.txt README || exit 0
-$(NAME).pdf: $(NAME).dtx
-	$(FORMAT) -shell-escape -recorder -interaction=batchmode $(NAME).dtx >/dev/null
-	if [ -f $(NAME).glo ]; then makeindex -q -s gglo.ist -o $(NAME).gls $(NAME).glo; fi
-	if [ -f $(NAME).idx ]; then makeindex -q -s gind.ist -o $(NAME).ind $(NAME).idx; fi
-	$(FORMAT) --recorder --interaction=nonstopmode $(NAME).dtx > /dev/null
-	$(FORMAT) --recorder --interaction=nonstopmode $(NAME).dtx > /dev/null
-clean:
-	rm -f $(NAME).{aux,fls,glo,gls,hd,idx,ilg,ind,ins,log,out}
-distclean: clean
-	rm -f $(NAME).{pdf,%ext%} README
-inst: all
-	mkdir -p $(UTREE)/{tex,source,doc}/latex/$(NAME)
-	cp $(NAME).dtx $(UTREE)/source/latex/$(NAME)
-	cp $(NAME).%ext% $(UTREE)/tex/latex/$(NAME)
-	cp $(NAME).pdf $(UTREE)/doc/latex/$(NAME)
-install: all
-	sudo mkdir -p $(LOCAL)/{tex,source,doc}/latex/$(NAME)
-	sudo cp $(NAME).dtx $(LOCAL)/source/latex/$(NAME)
-	sudo cp $(NAME).%ext% $(LOCAL)/tex/latex/$(NAME)
-	sudo cp $(NAME).pdf $(LOCAL)/doc/latex/$(NAME)
-zip: all
-	ln -sf . $(NAME)
-	zip -Drq $(PWD)/$(NAME)-$(VERS).zip $(NAME)/{README,$(NAME).{pdf,dtx}}
-	rm $(NAME)
-Makefile
-
-:<<'DTX'
-% \iffalse meta-comment
-% vim: textwidth=75
-%<*internal>
-\iffalse
-%</internal>
-%<*readme>
-|
-%readme%
-
-Short description:
-Some text about the %typ%: probably the same as the abstract.
-%</readme>
-%<*internal>
-\fi
-\def\nameofplainTeX{plain}
-\ifx\fmtname\nameofplainTeX\else
-  \expandafter\begingroup
-\fi
-%</internal>
-%<*install>
-\input docstrip.tex
-\keepsilent
-\askforoverwritefalse
-\preamble
-%readme%
-\endpreamble
-\postamble
-
-Copyright (C) %year% by %name% <%mail%>
-
-This work may be distributed and/or modified under the
-conditions of the LaTeX Project Public License (LPPL), either
-version 1.3c of this license or (at your option) any later
-version.  The latest version of this license is in the file:
-
-http://www.latex-project.org/lppl.txt
-
-This work is "maintained" (as per LPPL maintenance status) by
-%name%.
-
-This work consists of the file %base%.dtx and a Makefile.
-Running "make" generates the derived files README, %base%.pdf and %base%.%ext%.
-Running "make inst" installs the files in the user's TeX tree.
-Running "make install" installs the files in the local TeX tree.
-
-\endpostamble
-
-\usedir{tex/latex/%base%}
-\generate{
-  \file{\jobname.%ext%}{\from{\jobname.dtx}{%typ%}}
-}
-%</install>
-%<install>\endbatchfile
-%<*internal>
-\usedir{source/latex/%base%}
-\generate{
-  \file{\jobname.ins}{\from{\jobname.dtx}{install}}
-}
-\nopreamble\nopostamble
-\usedir{doc/latex/%base%}
-\generate{
-  \file{README.txt}{\from{\jobname.dtx}{readme}}
-}
-\ifx\fmtname\nameofplainTeX
-  \expandafter\endbatchfile
-\else
-  \expandafter\endgroup
-\fi
-%</internal>
-% \fi
-%
-% \iffalse
-%<*driver>
-\ProvidesFile{%base%.dtx}
-%</driver>
-%<%typ%>\NeedsTeXFormat{LaTeX2e}[1999/12/01]
-%<%typ%>\Provides%Typ%{%base%}
-%<*%typ%>
-    [%date% v1.00 %shrt%]
-%</%typ%>
-%<*driver>
-\documentclass{ltxdoc}
-\usepackage[a4paper,margin=25mm,left=50mm,nohead]{geometry}
-\usepackage[numbered]{hypdoc}
-%use%
-\EnableCrossrefs
-\CodelineIndex
-\RecordChanges
-\begin{document}
-  \DocInput{\jobname.dtx}
-\end{document}
-%</driver>
-% \fi
-%
-% \GetFileInfo{\jobname.dtx}
-% \DoNotIndex{\newcommand,\newenvironment}
-%
-%\title{\textsf{%base%} --- %short%\thanks{This file
-%   describes version \fileversion, last revised \filedate.}
-%}
-%\author{%name%\thanks{E-mail: %mail%}}
-%\date{Released \filedate}
-%
-%\maketitle
-%
-%\changes{v1.00}{%date%}{First public release}
-%
-% \begin{abstract}
-% ==== Put abstract text here. ====
-% \end{abstract}
-%
-% \section{Usage}
-%
-% ==== Put descriptive text here. ====
-%
+:<<'DESC'
 % \DescribeMacro{\dummyMacro}
 % This macro does nothing.\index{doing nothing|usage} It is merely an
 % example.  If this were a real macro, you would put a paragraph here
@@ -452,17 +309,9 @@ Running "make install" installs the files in the local TeX tree.
 % If this were a real environment, you would put a paragraph here
 % describing what the environment is supposed to do, what its
 % mandatory and optional arguments are, and so forth.
-%
-%\StopEventually{^^A
-%  \PrintChanges
-%  \PrintIndex
-%}
-%
-% \section{Implementation}
-%
-%    \begin{macrocode}
-%<*%typ%>
-%lcl%
+DESC
+
+:<<'BODY'
 %    \end{macrocode}
 % \begin{macro}{\dummyMacro}
 % This is a dummy macro.  If it did anything, we'd describe its
@@ -491,10 +340,173 @@ Running "make install" installs the files in the local TeX tree.
 }
 %    \end{macrocode}
 % \end{environment}
+%    \begin{macrocode}
+BODY
+
+:<<'MAKE'
+NAME  = $base
+SHELL = bash
+PWD   = $(shell pwd)
+FORMAT= $format
+VERS  = $(shell ltxfileinfo -v $(NAME).dtx|sed -e 's/^v//')
+LOCAL = $(shell kpsewhich --var-value TEXMFLOCAL)
+UTREE = $(shell kpsewhich --var-value TEXMFHOME)
+all:	$(NAME).pdf
+$(NAME).pdf: $(NAME).dtx
+	test -e Makefile || mv Makefile{.,}
+	$(FORMAT) -shell-escape -recorder -interaction=batchmode $(NAME).dtx >/dev/null
+	if [ -f $(NAME).glo ]; then makeindex -q -s gglo.ist -o $(NAME).gls $(NAME).glo; fi
+	if [ -f $(NAME).idx ]; then makeindex -q -s gind.ist -o $(NAME).ind $(NAME).idx; fi
+	$(FORMAT) --recorder --interaction=nonstopmode $(NAME).dtx > /dev/null
+	$(FORMAT) --recorder --interaction=nonstopmode $(NAME).dtx > /dev/null
+clean:
+	rm -f $(NAME).{aux,fls,glo,gls,hd,idx,ilg,ind,ins,log,out} Makefile. BODY
+distclean: clean
+	rm -f $(NAME).{pdf,$ext} README.md Makefile
+inst: all
+	mkdir -p $(UTREE)/{tex,source,doc}/latex/$(NAME)
+	cp $(NAME).dtx $(UTREE)/source/latex/$(NAME)
+	cp $(NAME).$ext $(UTREE)/tex/latex/$(NAME)
+	cp $(NAME).pdf README.md $(UTREE)/doc/latex/$(NAME)
+install: all
+	sudo mkdir -p $(LOCAL)/{tex,source,doc}/latex/$(NAME)
+	sudo cp $(NAME).dtx $(LOCAL)/source/latex/$(NAME)
+	sudo cp $(NAME).$ext $(LOCAL)/tex/latex/$(NAME)
+	sudo cp $(NAME).pdf README.md $(LOCAL)/doc/latex/$(NAME)
+zip: all
+	ln -sf . $(NAME)
+	zip -Drq $(PWD)/$(NAME)-$(VERS).zip $(NAME)/{README.md,$(NAME).{pdf,dtx}}
+	rm $(NAME)
+MAKE
+
+:<<'README'
+---------|----------------------------------------------------------------
+  $base: | $shrt
+ Author: | $name
+ E-mail: | $mail
+License: | Released under the LaTeX Project Public License v1.3c or later
+    See: | http://www.latex-project.org/lppl.txt
+
+Short description:
+Some text about the $typ: probably the same as the abstract.
+
+Installation:
+This is a self-extracting file. Install as follows:
+1. Run "luatex $base.dtx.
+2. Run "make -f Makefile." (don't forget the .)
+3. Run "make install" if you have sudo rights, to install in the local tree, or
+   Run "make inst" to install in your own tree.
+4. Run "make clean" to remove most intermdiate files, or
+   Run "make distclean" to keep the source, $base.dtx, only.
+README
+
+:<<'DTX'
+% \iffalse meta-comment
+%
+% Copyright (C) 2021 by Wybo Dekker <wybo@dekkerdocumenten.nl>
+%
+% This work may be distributed and/or modified under the
+% conditions of the LaTeX Project Public License (LPPL), either
+% version 1.3c of this license or (at your option) any later
+% version.  The latest version of this license is in the file:
+%
+% http://www.latex-project.org/lppl.txt
+%
+% This work consists of the self-extracting file $base.dtx
+% Installation: see the readme section above.
+%
+%<*internal>
+\iffalse
+%</internal>
+%<*readme>
+|
+$readme
+%</readme>
+%<*makefile>
+$makefile
+%</makefile>
+%<*internal>
+\fi
+\def\nameofplainTeX{plain}
+\ifx\fmtname\nameofplainTeX\else
+  \expandafter\begingroup
+\fi
+%</internal>
+%<*install>
+\input docstrip.tex
+\keepsilent
+\askforoverwritefalse
+
+\generate{\file{\jobname.$ext}{\from{\jobname.dtx}{$typ}}}
+%</install>
+%<install>\endbatchfile
+%<*internal>
+\nopreamble\nopostamble
+\catcode9=12
+\generate{\file{README.md}{\from{\jobname.dtx}{readme}}}
+\generate{\file{Makefile.}{\from{\jobname.dtx}{makefile}}}
+\ifx\fmtname\nameofplainTeX
+  \expandafter\endbatchfile
+\else
+  \expandafter\endgroup
+\fi
+%</internal>
+% \fi
+%
+% \iffalse
+%<*driver>
+\ProvidesFile{$base.dtx}
+%</driver>
+%<$typ>\NeedsTeXFormat{LaTeX2e}[2021/11/15]
+%<$typ>\Provides$Typ{$base}
+%<*$typ>
+    [$date v1.00 $shrt]
+%</$typ>
+%<*driver>
+\documentclass{ltxdoc}
+\usepackage[a4paper,margin=25mm,left=50mm,nohead]{geometry}
+\usepackage[numbered]{hypdoc}
+$use
+\EnableCrossrefs
+\CodelineIndex
+\RecordChanges
+\begin{document}
+  \DocInput{\jobname.dtx}
+\end{document}
+%</driver>
+% \fi
+%
+% \GetFileInfo{\jobname.sty}
+% \DoNotIndex{\newcommand,\newenvironment}
+%
+% \title{\textsf{$base} --- $short\\[3ex]
+%   \large\fileversion\quad\filedate}
+% \author{$name\thanks{E-mail: $mail}}
+% \date{}
+% \maketitle
+%
+% \changes{v1.00}{$date}{First public release}
+%
+% \begin{abstract}
+$abst
+% \end{abstract}
+%
+% \section{Usage}
+$desc
+% \StopEventually{^^A
+% \PrintChanges
+% \PrintIndex
+
+%}
+%
+% \section{Implementation}
 %
 %    \begin{macrocode}
+%<*$typ>
+$lcl
+$body
 \endinput
-%</%typ%>
+%</$typ>
 %    \end{macrocode}
 %\Finale
 DTX
